export enum AvroTicketStatus {
  AVAILABLE = 'AVAILABLE',

  BOOKED = 'BOOKED',

  CANCELLED = 'CANCELLED',

  EXPIRED = 'EXPIRED',

  EXCHANGE_REQUESTED = 'EXCHANGE_REQUESTED',

  EXCHANGE_APPROVED = 'EXCHANGE_APPROVED',

  EXCHANGE_REJECTED = 'EXCHANGE_REJECTED',

  EXCHANGE_COMPLETED = 'EXCHANGE_COMPLETED',

  REFUND_REQUESTED = 'REFUND_REQUESTED',

  REFUND_APPROVED = 'REFUND_APPROVED',

  REFUND_REJECTED = 'REFUND_REJECTED',

  REFUND_COMPLETED = 'REFUND_COMPLETED',

  REFUND_FAILED = 'REFUND_FAILED',
}
