export enum BookingStatus {
  DRAFT = 'DRAFT',

  AWAITING_PAYMENT = 'AWAITING_PAYMENT',

  PAID = 'PAID',

  CONFIRMED = 'CONFIRMED',

  CANCELED = 'CANCELED',

  REFUNDED = 'REFUNDED',

  RECOVERY_FAILED_SEAT_LOCKS = 'RECOVERY_FAILED_SEAT_LOCKS',
}
