export enum ExchangeStatus {
  EXCHANGE_REQUESTED = 'EXCHANGE_REQUESTED',

  EXCHANGE_APPROVED = 'EXCHANGE_APPROVED',

  EXCHANGE_REJECTED = 'EXCHANGE_REJECTED',

  EXCHANGE_COMPLETED = 'EXCHANGE_COMPLETED',
}
