export enum PaymentStatus {
  INITIATED = 'INITIATED',

  PROCESSING = 'PROCESSING',

  SUCCESS = 'SUCCESS',

  FAILED = 'FAILED',

  REFUNDED = 'REFUNDED',

  PAYMENT_SUCCESS_BUT_BOOKING_EXPIRED = 'PAYMENT_SUCCESS_BUT_BOOKING_EXPIRED',

  REQUIRES_MANUAL_REVIEW = 'REQUIRES_MANUAL_REVIEW',
}
