export enum RefundStatus {
  REFUND_REQUESTED = 'REFUND_REQUESTED',

  REFUND_APPROVED = 'REFUND_APPROVED',

  REFUND_REJECTED = 'REFUND_REJECTED',

  REFUND_COMPLETED = 'REFUND_COMPLETED',

  REFUND_FAILED = 'REFUND_FAILED',
}
